language: go
dist: trusty
go:
  - 1.11.x
  - 1.12.x
addons:
  apt:
    packages:
      - zsh
before_script:
  - go get ./...
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - golangci-lint run
  - make all
