language: go
dist: trusty
go:
- 1.11.x
- master
addons:
  apt:
    packages:
    - zsh
before_script:
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
- golangci-lint run
