version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\urfave\gfmxr

environment:
  GOPATH: C:\gopath
  GOVERSION: 1.6
  GFMXR_DEBUG: 1

install:
  - set PATH=%GOPATH%\bin;C:\go\bin;C:\MinGW\bin;%PATH%
  - go version
  - go env
  - go get -v -t ./...
  - ps: ls C:\MinGW\bin
  - mingw-get install mingw32-make

build_script:
  - make

test: off

deploy: off
